export const liability = `FRC Kickoff has officially started, and with it comes the annual ritual of equal parts excitement, optimism, and immediate existential dread. The game reveal drops, the animation ends, and suddenly every team in the room is convinced they both fully understand the challenge and are already hopelessly behind. Whiteboards fill with arrows, mentors start saying “in past years…,” and someone inevitably asks whether the robot *really* needs to do all of that. This is the moment where ambition meets reality, and reality politely reminds everyone that build season is undefeated.

In the spirit of the LWT (Good Luck With That) Public License, this phase of the season is defined by bold decisions made with incomplete information. Strategies are proposed, debated, scrapped, resurrected, and rewritten before lunch. Code is planned that nobody fully understands yet, mechanisms are sketched that “should work in theory,” and timelines are created with a straight face despite everyone knowing they will be ignored by Week 3. It might just work—or it might not. There is, as always, no third option.

As development begins, the license’s core principle becomes painfully relevant: everyone is free to do whatever they want, entirely at their own risk. Want to try a novel drivetrain? Go for it. A brand-new control architecture? Absolutely. A mechanism that relies on tolerances tighter than your shop tools can realistically achieve? That’s a choice. No warranties are implied, no guarantees are provided, and any resemblance to a polished, competition-ready robot before bag day is purely coincidental.

Crucially, responsibility is carefully and enthusiastically disclaimed. When something breaks, catches fire, or behaves in a way no one can logically explain, the blame shall not be traced back to kickoff hype, late-night design sessions, or that one commit made at 2:47 a.m. The robot does what it does, the code does what it feels like, and the team moves forward regardless. Liability is waived; lessons are learned the hard way.

And yet, despite all of this, the magic of kickoff remains intact. Against all odds—and often against their own better judgment—teams will iterate, adapt, and improve. The robot will eventually drive, score, and maybe even do so reliably. In the end, FRC Kickoff isn’t about certainty or guarantees; it’s about creativity, resilience, and embracing the chaos with confidence.

Good luck with that. Godspeed.` // rohan approved this
// delete after kickoff
